<?xml version='1.0'?>

<robot name="marvin" xmlns:xacro="http://www.ros.org/wiki/xacro"> 
    <!-- Includes -->
    <xacro:include filename="$(find simulation_marvin)/urdf/constants.xacro"/>

	<!-- Base_link -->
    <link name="base_link" />


    <!-- Footprint -->
    <link name="base_footprint" />  

    <joint name="base_joint" type="fixed">
        <origin xyz="0 0 ${-chassis_z_offset}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="base_footprint" />
    </joint>


    <!-- Chassis -->
    <xacro:include filename="$(find simulation_marvin)/urdf/chassis.xacro"/>


    <!-- Caster -->
    <xacro:include filename="$(find simulation_common)/urdf/wheel/caster.xacro"/>
	<xacro:caster name="caster">
        <origin xyz="${caster_x_offset} 0 ${caster_z_offset}" rpy="0 0 0" />
	</xacro:caster>


    <!-- Wheels -->
    <xacro:include filename="$(find simulation_common)/urdf/wheel/wheel.xacro"/>
	<xacro:wheel name="right_wheel">
		<origin xyz="0 ${-wheel_x_offset} ${wheel_z_offset}" rpy="0 0 0" />
	</xacro:wheel>
	<xacro:wheel name="left_wheel">
		<origin xyz="0 ${wheel_x_offset} ${wheel_z_offset}" rpy="0 0 0" />
	</xacro:wheel>


    <!-- Camera -->
	<xacro:include filename="$(find simulation_common)/urdf/sensor/depth_camera.xacro" />
	<xacro:depth_camera name="zed">
		<origin xyz="${camera_x_offset} 0 ${camera_z_offset}" rpy="0 ${camera_angle} 0" />
	</xacro:depth_camera>


    <!-- Lidar -->
    <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro" />
	<xacro:VLP-16 parent="base_link" name="velodyne" topic="/velodyne_points" hz="20" samples="440" gpu="true">
		<origin xyz="0 0 ${lidar_z_offset}" rpy="0 0 0" />
	</xacro:VLP-16>


	<!-- IMU -->
    <xacro:include filename="$(find simulation_common)/urdf/sensor/imu.xacro" />
    <xacro:imu name="imu">
		<origin xyz="${-chassis_tower_length / 2 - chassis_electrical_length/2} 0 ${chassis_electrical_height}" rpy="0 0 0" />
    </xacro:imu>


    <!-- Encoder -->
    <link name="encoder" />

	<joint name="encoder_joint" type="fixed">
		<origin xyz="0 0 ${wheel_z_offset}" rpy="0 0 0" />
		<parent link="base_link" />
		<child link="encoder" />
		<axis xyz="0 1 0" />
	</joint>

    <gazebo reference="base_link">
        <sensor name="GPS" type="gps">
            <always_on>true</always_on>
            <update_rate>10</update_rate>
            <plugin name="GPS_Controller" filename="libgazebo_ros_gps_sensor.so">
                <ros>
                    <!-- publish to /gps/data -->
                    <namespace>/gps</namespace>
                    <remapping>~/out:=data</remapping>
                </ros>
        </plugin>
        </sensor>
    </gazebo>


    <!-- Differential Drive -->
    	<gazebo>
		<plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
			<update_rate>100.0</update_rate>
			<robot_base_frame>base_link</robot_base_frame>
			<command_topic>cmd_vel</command_topic>

			<left_joint>left_wheel_joint</left_joint>
			<right_joint>right_wheel_joint</right_joint>
			<wheel_separation>${2 * wheel_x_offset}</wheel_separation>
			<wheel_diameter>${2 * 6.1875 * 0.0254}</wheel_diameter>
			<publish_tf>true</publish_tf>
			<publish_wheel_tf>true</publish_wheel_tf>

			<max_wheel_acceleration>1.8</max_wheel_acceleration>
			<max_wheel_torque>30</max_wheel_torque>

			<odometrySource>encoder</odometrySource>
			<odometry_topic>odom</odometry_topic>
			<odometry_frame>odom</odometry_frame>
			<publish_odom>true</publish_odom>
			<publish_odom_tf>true</publish_odom_tf>

			<legacy_mode>false</legacy_mode>
			<ros_debug_level>na</ros_debug_level>
		</plugin>
	</gazebo>
</robot>