<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="depth_camera">
    <xacro:macro name="depth_camera" params="prefix mass length width height parent:=base_link *joint_origin">
        <xacro:include filename="$(find marvin_simulation)/urdf/inertia.xacro"/>

        <link name="${prefix}_depth_camera_link">
            <xacro:box_inertia mass="${mass}" length="${length}" width="${width}" height="${height}">
                <origin xyz="0 0 0" rpy="0 0 0" />
            </xacro:box_inertia>
    
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
            </visual>
    
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
            </collision>
        </link>
    
        <link name="${prefix}_depth_camera_optical_link" />
        
        <joint name="${prefix}_depth_camera_optical_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
            <parent link="${prefix}_depth_camera_link" />
            <child link="${prefix}_depth_camera_optical_link" />
        </joint>

        <link name="${prefix}_depth_camera_base_link" />

        <joint name="${prefix}_depth_camera_joint" type="fixed">
            <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
            <parent link="${prefix}_depth_camera_base_link" />
            <child link="${prefix}_depth_camera_link" />
        </joint>

        <joint name="${prefix}_depth_camera_base_joint" type="fixed">
            <xacro:insert_block name="joint_origin" />
            <parent link="${parent}" />
            <child link="${prefix}_depth_camera_base_link" />
            <axis xyz="0 1 0" />
        </joint>
    
        <gazebo reference="${prefix}_depth_camera">
            <material>Gazebo/Yellow</material>
        </gazebo>

        <gazebo reference="${prefix}_depth_camera">
            <sensor type="depth" name="camera1">
            <update_rate>15.0</update_rate>
            <camera name="head">
                <horizontal_fov>1.91986</horizontal_fov>
                <image>
                <width>2560</width>
                <height>720</height>
                <format>R8G8B8</format>
                </image>
                <clip>
                <near>0.02</near>
                <far>300</far>
                </clip>
            </camera>
            <!-- change the plugin to a depth cam-->
            <plugin name="${prefix}_depth_camera_plugin" filename="libgazebo_ros_openni_kinect.so">
                <baseline>0.2</baseline>
                <alwaysOn>true</alwaysOn>
                <!-- Keep this zero, update_rate in the parent <sensor> tag
                will control the frame rate. -->
                <updateRate>0.0</updateRate>
                <cameraName>camera_ir</cameraName>
                <imageTopicName>/camera/color/image_raw</imageTopicName>
                <cameraInfoTopicName>/camera/color/camera_info</cameraInfoTopicName>
                <depthImageTopicName>/camera/depth/image_raw</depthImageTopicName>
                <depthImageCameraInfoTopicName>/camera/depth/camera_info</depthImageCameraInfoTopicName>
                <pointCloudTopicName>/camera/depth/points</pointCloudTopicName> <!-- /camera/depth/points -->
                <frameName>camera_link_optical</frameName>
                <pointCloudCutoff>0.3</pointCloudCutoff>
                <pointCloudCutoffMax>20</pointCloudCutoffMax>
                <distortionK1>0</distortionK1>
                <distortionK2>0</distortionK2>
                <distortionK3>0</distortionK3>
                <distortionT1>0</distortionT1>
                <distortionT2>0</distortionT2>
                <CxPrime>0</CxPrime>
                <Cx>0</Cx>
                <Cy>0</Cy>
                <focalLength>0</focalLength>
                <hackBaseline>0</hackBaseline>
            </plugin>
            </sensor>
        </gazebo>
    </xacro:macro>
</robot>