<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="depth_camera">
    <xacro:macro name="depth_camera" params="prefix mass length width height parent *joint_origin">
        <xacro:include filename="$(find marvin_simulation)/urdf/inertia.xacro"/>

        <link name="${prefix}_depth_camera">
            <xacro:box_inertia mass="${mass}" length="${length}" width="${width}" height="${height}">
                <origin xyz="0 0 ${height/2}" rpy="0 0 0" />
            </xacro:box_inertia>
    
            <visual>
                <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
            </visual>
    
            <collision>
                <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
            </collision>
        </link>
    
        <link name="${prefix}_depth_camera_optical_link" />
        
        <joint name="${prefix}_depth_camera_optical_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
            <parent link="${prefix}_depth_camera" />
            <child link="${prefix}_depth_camera_optical_link" />
        </joint>

        <joint name="${prefix}_depth_camera_joint" type="fixed">
            <xacro:insert_block name="joint_origin" />
            <parent link="${parent}" />
            <child link="${prefix}_depth_camera" />
            <axis xyz="0 1 0" />
        </joint>
    
        <gazebo reference="${prefix}_depth_camera">
            <material>Gazebo/Yellow</material>
        </gazebo>
    </xacro:macro>
</robot>