<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="depth_camera">
    <xacro:macro name="depth_camera" params="prefix mass length width height parent:=base_link *joint_origin">
        <xacro:include filename="$(find marvin_simulation)/urdf/inertia.xacro"/>

        <!-- Depth camera base link -->
        <link name="${prefix}_depth_camera_base_link" />

        <joint name="${prefix}_depth_camera_base_joint" type="fixed">
            <xacro:insert_block name="joint_origin" />
            <parent link="${parent}" />
            <child link="${prefix}_depth_camera_base_link" />
            <axis xyz="0 1 0" />
        </joint>


        <!-- Depth camera link -->
        <link name="${prefix}_depth_camera_link">
            <xacro:box_inertia mass="${mass}" length="${length}" width="${width}" height="${height}">
                <origin xyz="0 0 0" rpy="0 0 0" />
            </xacro:box_inertia>
    
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
            </visual>
    
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
            </collision>
        </link>
    
        <joint name="${prefix}_depth_camera_joint" type="fixed">
            <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
            <parent link="${prefix}_depth_camera_base_link" />
            <child link="${prefix}_depth_camera_link" />
        </joint>


        <!-- Depth camera optical link -->
        <link name="${prefix}_depth_camera_optical_link" />
        
        <joint name="${prefix}_depth_camera_optical_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
            <parent link="${prefix}_depth_camera_link" />
            <child link="${prefix}_depth_camera_optical_link" />
        </joint>

        <!-- Depth camera color -->    
        <gazebo reference="${prefix}_depth_camera_link">
            <material>Gazebo/Black</material>
        </gazebo>


        <!-- Depth camera plugin -->
        <gazebo reference="${prefix}_depth_camera_link">
            <sensor name="${prefix}_depth_camera" type="depth">
                <update_rate>10.0</update_rate>
                <visualize>true</visualize>
                <always_on>true</always_on>

                <camera>
                    <horizontal_fov>1.91986</horizontal_fov>
                    <image>
                        <width>640</width>
                        <height>480</height>
                        <format>B8G8R8</format>
                    </image>
                    <clip>
                        <near>0.05</near>
                        <far>8.0</far>
                    </clip>
                </camera>

                <plugin name="${prefix}_depth_camera_controller" filename="libgazebo_ros_camera.so">
                    <frame_name>${prefix}_depth_camera_optical_link</frame_name>
                    <min_depth>0.1</min_depth>
                    <max_depth>100.0</max_depth>
                </plugin>
            </sensor>
        </gazebo>
    </xacro:macro>
</robot>